"""initial_schema

Revision ID: 1fe3ed53b4de
Revises: 
Create Date: 2026-04-03 22:58:52.315135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe3ed53b4de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nba_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('team_abbreviation', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_nba_id'), 'players', ['nba_id'], unique=True)
    op.create_table('game_play_type_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('isolation_poss', sa.Integer(), nullable=True),
    sa.Column('isolation_pts', sa.Integer(), nullable=True),
    sa.Column('isolation_fgm', sa.Integer(), nullable=True),
    sa.Column('isolation_fga', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_poss', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_pts', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_fgm', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_fga', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_poss', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_pts', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_fgm', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_fga', sa.Integer(), nullable=True),
    sa.Column('post_up_poss', sa.Integer(), nullable=True),
    sa.Column('post_up_pts', sa.Integer(), nullable=True),
    sa.Column('post_up_fgm', sa.Integer(), nullable=True),
    sa.Column('post_up_fga', sa.Integer(), nullable=True),
    sa.Column('spot_up_poss', sa.Integer(), nullable=True),
    sa.Column('spot_up_pts', sa.Integer(), nullable=True),
    sa.Column('spot_up_fgm', sa.Integer(), nullable=True),
    sa.Column('spot_up_fga', sa.Integer(), nullable=True),
    sa.Column('spot_up_fg3m', sa.Integer(), nullable=True),
    sa.Column('spot_up_fg3a', sa.Integer(), nullable=True),
    sa.Column('transition_poss', sa.Integer(), nullable=True),
    sa.Column('transition_pts', sa.Integer(), nullable=True),
    sa.Column('transition_fgm', sa.Integer(), nullable=True),
    sa.Column('transition_fga', sa.Integer(), nullable=True),
    sa.Column('cut_poss', sa.Integer(), nullable=True),
    sa.Column('cut_pts', sa.Integer(), nullable=True),
    sa.Column('cut_fgm', sa.Integer(), nullable=True),
    sa.Column('cut_fga', sa.Integer(), nullable=True),
    sa.Column('off_screen_poss', sa.Integer(), nullable=True),
    sa.Column('off_screen_pts', sa.Integer(), nullable=True),
    sa.Column('off_screen_fgm', sa.Integer(), nullable=True),
    sa.Column('off_screen_fga', sa.Integer(), nullable=True),
    sa.Column('total_poss', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_play_type_stats_game_date'), 'game_play_type_stats', ['game_date'], unique=False)
    op.create_index(op.f('ix_game_play_type_stats_game_id'), 'game_play_type_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_play_type_stats_player_id'), 'game_play_type_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_game_play_type_stats_season'), 'game_play_type_stats', ['season'], unique=False)
    op.create_table('player_advanced_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('ts_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('efg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('usg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('off_rating', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('def_rating', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('net_rating', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('pace', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pie', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('ast_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('ast_to', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ast_ratio', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('oreb_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('dreb_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('reb_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('tm_tov_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_advanced_stats_player_id'), 'player_advanced_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_advanced_stats_season'), 'player_advanced_stats', ['season'], unique=False)
    op.create_table('player_career_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('ppg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('rpg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('apg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('spg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bpg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('fg3_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('ft_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('team_abbreviation', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_career_stats_player_id'), 'player_career_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_career_stats_season'), 'player_career_stats', ['season'], unique=False)
    op.create_table('player_clutch_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pts', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fgm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fga', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('fg3m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg3a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fg3_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('ftm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ft_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('ast', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reb', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stl', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tov', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('plus_minus', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('net_rating', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_clutch_stats_player_id'), 'player_clutch_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_clutch_stats_season'), 'player_clutch_stats', ['season'], unique=False)
    op.create_table('player_computed_advanced',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('per', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('obpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dbpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vorp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ows', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dws', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ws', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ws_per_48', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('radar_scoring', sa.Integer(), nullable=True),
    sa.Column('radar_playmaking', sa.Integer(), nullable=True),
    sa.Column('radar_defense', sa.Integer(), nullable=True),
    sa.Column('radar_efficiency', sa.Integer(), nullable=True),
    sa.Column('radar_volume', sa.Integer(), nullable=True),
    sa.Column('radar_durability', sa.Integer(), nullable=True),
    sa.Column('radar_clutch', sa.Integer(), nullable=True),
    sa.Column('radar_versatility', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_computed_advanced_player_id'), 'player_computed_advanced', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_computed_advanced_season'), 'player_computed_advanced', ['season'], unique=False)
    op.create_table('player_defensive_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('overall_d_fgm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('overall_d_fga', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('overall_d_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('overall_normal_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('overall_pct_plusminus', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('rim_d_fgm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rim_d_fga', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rim_d_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('rim_normal_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('rim_pct_plusminus', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('three_pt_d_fgm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('three_pt_d_fga', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('three_pt_d_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('three_pt_normal_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('three_pt_pct_plusminus', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('iso_poss', sa.Integer(), nullable=True),
    sa.Column('iso_pts', sa.Integer(), nullable=True),
    sa.Column('iso_fgm', sa.Integer(), nullable=True),
    sa.Column('iso_fga', sa.Integer(), nullable=True),
    sa.Column('iso_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('iso_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('iso_percentile', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_defensive_stats_player_id'), 'player_defensive_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_defensive_stats_season'), 'player_defensive_stats', ['season'], unique=False)
    op.create_table('player_shooting_tracking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('catch_shoot_fgm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('catch_shoot_fga', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('catch_shoot_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('catch_shoot_fg3m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('catch_shoot_fg3a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('catch_shoot_fg3_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('catch_shoot_pts', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('catch_shoot_efg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pullup_fgm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pullup_fga', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pullup_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pullup_fg3m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pullup_fg3a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pullup_fg3_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pullup_pts', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pullup_efg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('drives', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('drive_fgm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('drive_fga', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('drive_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('drive_pts', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('drive_ast', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('drive_tov', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_shooting_tracking_player_id'), 'player_shooting_tracking', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_shooting_tracking_season'), 'player_shooting_tracking', ['season'], unique=False)
    op.create_table('player_shot_zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('fgm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fga', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('league_avg', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_shot_zones_player_id'), 'player_shot_zones', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_shot_zones_season'), 'player_shot_zones', ['season'], unique=False)
    op.create_table('season_play_type_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('total_poss', sa.Integer(), nullable=True),
    sa.Column('isolation_poss', sa.Integer(), nullable=True),
    sa.Column('isolation_pts', sa.Integer(), nullable=True),
    sa.Column('isolation_fgm', sa.Integer(), nullable=True),
    sa.Column('isolation_fga', sa.Integer(), nullable=True),
    sa.Column('isolation_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('isolation_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('isolation_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('isolation_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_poss', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_pts', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_fgm', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_fga', sa.Integer(), nullable=True),
    sa.Column('pnr_ball_handler_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pnr_ball_handler_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pnr_ball_handler_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pnr_ball_handler_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_poss', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_pts', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_fgm', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_fga', sa.Integer(), nullable=True),
    sa.Column('pnr_roll_man_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pnr_roll_man_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pnr_roll_man_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pnr_roll_man_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('post_up_poss', sa.Integer(), nullable=True),
    sa.Column('post_up_pts', sa.Integer(), nullable=True),
    sa.Column('post_up_fgm', sa.Integer(), nullable=True),
    sa.Column('post_up_fga', sa.Integer(), nullable=True),
    sa.Column('post_up_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('post_up_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('post_up_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('post_up_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('spot_up_poss', sa.Integer(), nullable=True),
    sa.Column('spot_up_pts', sa.Integer(), nullable=True),
    sa.Column('spot_up_fgm', sa.Integer(), nullable=True),
    sa.Column('spot_up_fga', sa.Integer(), nullable=True),
    sa.Column('spot_up_fg3m', sa.Integer(), nullable=True),
    sa.Column('spot_up_fg3a', sa.Integer(), nullable=True),
    sa.Column('spot_up_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('spot_up_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('spot_up_fg3_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('spot_up_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('spot_up_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('transition_poss', sa.Integer(), nullable=True),
    sa.Column('transition_pts', sa.Integer(), nullable=True),
    sa.Column('transition_fgm', sa.Integer(), nullable=True),
    sa.Column('transition_fga', sa.Integer(), nullable=True),
    sa.Column('transition_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('transition_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('transition_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('transition_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('cut_poss', sa.Integer(), nullable=True),
    sa.Column('cut_pts', sa.Integer(), nullable=True),
    sa.Column('cut_fgm', sa.Integer(), nullable=True),
    sa.Column('cut_fga', sa.Integer(), nullable=True),
    sa.Column('cut_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('cut_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('cut_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('cut_ppp_percentile', sa.Integer(), nullable=True),
    sa.Column('off_screen_poss', sa.Integer(), nullable=True),
    sa.Column('off_screen_pts', sa.Integer(), nullable=True),
    sa.Column('off_screen_fgm', sa.Integer(), nullable=True),
    sa.Column('off_screen_fga', sa.Integer(), nullable=True),
    sa.Column('off_screen_ppp', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('off_screen_fg_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('off_screen_freq', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('off_screen_ppp_percentile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_play_type_stats_player_id'), 'season_play_type_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_season_play_type_stats_season'), 'season_play_type_stats', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_play_type_stats_season'), table_name='season_play_type_stats')
    op.drop_index(op.f('ix_season_play_type_stats_player_id'), table_name='season_play_type_stats')
    op.drop_table('season_play_type_stats')
    op.drop_index(op.f('ix_player_shot_zones_season'), table_name='player_shot_zones')
    op.drop_index(op.f('ix_player_shot_zones_player_id'), table_name='player_shot_zones')
    op.drop_table('player_shot_zones')
    op.drop_index(op.f('ix_player_shooting_tracking_season'), table_name='player_shooting_tracking')
    op.drop_index(op.f('ix_player_shooting_tracking_player_id'), table_name='player_shooting_tracking')
    op.drop_table('player_shooting_tracking')
    op.drop_index(op.f('ix_player_defensive_stats_season'), table_name='player_defensive_stats')
    op.drop_index(op.f('ix_player_defensive_stats_player_id'), table_name='player_defensive_stats')
    op.drop_table('player_defensive_stats')
    op.drop_index(op.f('ix_player_computed_advanced_season'), table_name='player_computed_advanced')
    op.drop_index(op.f('ix_player_computed_advanced_player_id'), table_name='player_computed_advanced')
    op.drop_table('player_computed_advanced')
    op.drop_index(op.f('ix_player_clutch_stats_season'), table_name='player_clutch_stats')
    op.drop_index(op.f('ix_player_clutch_stats_player_id'), table_name='player_clutch_stats')
    op.drop_table('player_clutch_stats')
    op.drop_index(op.f('ix_player_career_stats_season'), table_name='player_career_stats')
    op.drop_index(op.f('ix_player_career_stats_player_id'), table_name='player_career_stats')
    op.drop_table('player_career_stats')
    op.drop_index(op.f('ix_player_advanced_stats_season'), table_name='player_advanced_stats')
    op.drop_index(op.f('ix_player_advanced_stats_player_id'), table_name='player_advanced_stats')
    op.drop_table('player_advanced_stats')
    op.drop_index(op.f('ix_game_play_type_stats_season'), table_name='game_play_type_stats')
    op.drop_index(op.f('ix_game_play_type_stats_player_id'), table_name='game_play_type_stats')
    op.drop_index(op.f('ix_game_play_type_stats_game_id'), table_name='game_play_type_stats')
    op.drop_index(op.f('ix_game_play_type_stats_game_date'), table_name='game_play_type_stats')
    op.drop_table('game_play_type_stats')
    op.drop_index(op.f('ix_players_nba_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
